# Generated by Django 4.2.5 on 2023-09-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Main_Category',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
